- name: "Install on {{ ansible_distribution }}"
  become: true
  ansible.builtin.pacman:
    name:
      - "{{ role_name }}"
    state: latest
  when: (update | default(true)) | bool # Default to true if not defined

- name: "Check if default.conf exists"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/default.conf"
  register: default_conf
  when: (configure | default(true)) | bool  # Default to true if not defined

# - name: "Debug | default_conf"
#   ansible.builtin.debug:
#     var: default_conf
#   when: (configure | default(true)) | bool  # Default to true if not defined

- name: "Symlink default.conf to /etc/keyd/default.conf"
  become: true
  ansible.builtin.file:
    src: "{{ role_path }}/files/default.conf"
    dest: /etc/keyd/default.conf
    state: link
    force: true
  when: ((configure | default(true)) | bool) and default_conf.stat.exists

- name: "Reload the keyd daemon"
  ansible.builtin.command:
    cmd: "keyd reload"
  changed_when: false
  when: (configure | default(true)) | bool  # Default to true if not defined

- name: "Clear the default_conf Variable"
  ansible.builtin.set_fact:
    default_conf: null
  when: (configure | default(true)) | bool  # Default to true if not defined
