# constants
export HISTFILESIZE=10000
export HISTSIZE=10000
setopt INC_APPEND_HISTORY # command are directly entered in the HISTFILE instead of waiting for the shell to close
setopt HIST_FIND_NO_DUPS # removes the duplicates while searching
setopt HIST_IGNORE_ALL_DUPS # ignores all duplicates while writing in the hist file

# Add a directory to the PATH variable
addToPath ()
{
    if [ -d $1 ]; then
        export PATH=$1:$PATH
    fi
}

# plug = source
# Created by zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/supercharge"
plug "zsh-users/zsh-syntax-highlighting"

# Not generated by zsh added by Vivian
plug "${XDG_CONFIG_HOME}/zsh/zsh_prompt.zsh" # prompt for zsh
plug "${XDG_CONFIG_HOME}/zsh/zsh_aliases.zsh" # aliases for zsh
plug "${XDG_CONFIG_HOME}/zsh/plugins/*" # local plugins for zsh 
plug "${XDG_DATA_HOME}/bun/_bun" # autocompletion for bun

neofetch

# Load and initialise completion system
autoload -Uz compinit
compinit

#zoxide
eval "$(zoxide init zsh)"

# add to path
addToPath "$BUN_INSTALL/bin" #bun
addToPath "$XDG_DATA_HOME/go/bin" #go
addToPath "$GOPATH/bin" #go
addToPath "$XDG_DATA_HOME/tmux/plugins/tmuxifier/bin" #tmuxifier


# environment variables
export BUN_INSTALL="$XDG_DATA_HOME/bun" #bun
export TMUXIFIER_LAYOUT_PATH="$XDG_DATA_HOME/tmux/sessions" #tmuxifier

#vi mode
bindkey -v
