- name: "Install on {{ ansible_distribution }}"
  become: true
  ansible.builtin.pacman:
    name:
      - "{{ role_name }}"
    state: latest
  when: (update | default(true)) | bool # Default to true if not defined

- name: "Setup Config for {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - common_tasks/setup_config_dir_linux.yaml
  when: (configure | default(true)) | bool  # Default to true if not defined

- name: "Install the plugins"
  ansible.builtin.shell:
    cmd: "ya pack -i" # To install all the plugins with locked versions from package.toml on a new system
    creates: "{{ ansible_env.HOME }}/.config/yazi/plugins/"
  when: (configure | default(true)) | bool  # Default to true if not defined

- name: "Update the plugins"
  ansible.builtin.shell:
    cmd: "ya pack -u"
    creates: "{{ ansible_env.HOME }}/.config/yazi/plugins/"
  when: (update | default(true)) | bool  # Default to true if not defined
