# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    info title
    info underline

    info "╰─OS" distro
    # info "Host" model
    # info "Kernel" kernel
    info "╰─Packages" packages
    # info "Resolution" resolution
    # info "DE" de
    # info "Shell" shell
    # info "WM" wm
    # info "WM Theme" wm_theme
    # info "Theme" theme
    # info "Icons" icons
    # info "Terminal" term
    # info "Terminal Font" term_font
    # info "CPU" cpu
    # info "GPU" gpu
    # info "Uptime" uptime
    # info "CPU Usage" cpu_usage
    info "╰─Memory" memory
    info "╰─Disk" disk
    # info "Battery" battery
    # info "GPU Driver" gpu_driver  # Linux/macOS only
    # info "Font" font
    # info "Song" song
    [[ "$player" ]] && prin "Music Player" "$player"
    # info "Local IP" local_ip
    # info "Public IP" public_ip
    # info "Users" users
    # info "Locale" locale  # This only works on glibc systems.
    # info cols
    info underline
    prin "$(color 1) \n \n $(color 2) \n \n $(color 3) \n \n $(color 4) \n \n $(color 5) \n \n $(color 6) \n \n $(color 7) \n \n $(color 0) "
    # prin " \n \n $(color 9) \n \n $(color 10) \n \n $(color 11) \n \n $(color 12) \n \n $(color 13) \n \n $(color 14) \n \n $(color 15) \n \n $(color 0) "
}
seperator="<200b>"
distro_shorthand="off"
os_arch="off"
ascii_distro="arch_small"
colors=(5 2 5 4 4 7)
ascii_colors=(10 5)
ascii_bold="on"
