- name: "Install on {{ ansible_distribution }}"
  become: true
  ansible.builtin.pacman:
    name:
      - "{{ role_name }}"
    state: latest
  when: (update | default(true)) | bool # Default to true if not defined

- name: "Setup Config for {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - common_tasks/setup_config_dir_linux.yaml
    - common_tasks/setup_data_dir_linux.yaml
  when: (configure | default(true)) | bool  # Default to true if not defined

- name: "Source Config for {{ ansible_distribution }}"
  ansible.builtin.shell:
    cmd: "zsh -i -c 'source ${ZDOTDIR:-$HOME}/.zshrc'"
  when: (configure | default(true)) | bool  # Default to true if not defined
  changed_when: false

- name: "Install the plugins"
  ansible.builtin.shell:
    cmd: "zsh -i -c 'zap update all'"
  when: (configure | default(true)) | bool  # Default to true if not defined
  changed_when: false
