- name: "Install on {{ ansible_distribution }}"
  become: true
  ansible.builtin.pacman:
    name:
      - "{{ role_name }}"
    state: latest
  when: (update | default(true)) | bool # Default to true if not defined

- name: Clone TPM (Tmux Plugin Manager)
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('env', 'TMUX_PLUGIN_MANAGER_PATH') | default(ansible_env.HOME + '/.tmux/plugins/', true) }}tpm"
    update: true  # Update if the repository already exists

- name: "Setup Config for {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - common_tasks/setup_config_dir_linux.yaml
    - common_tasks/setup_data_dir_linux.yaml
  when: (configure | default(true)) | bool  # Default to true if not defined
