[[manager.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[manager.prepend_keymap]]
on = [ "g", "r" ]
run = '''
	shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
'''

[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Toggle Maximize preview pane"

[[manager.prepend_keymap]]
on   = [ "E" ]
run  = "plugin fuzzychild"

[[manager.prepend_keymap]]
on   = [ "e" ]
run = "plugin searchjump autocd"
desc = "searchjump mode auto jump"
