[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin --sync max-preview"
# For upcoming Yazi 0.4 (nightly version):
# run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = [ "E" ]
run  = "plugin child-dir"

[[manager.prepend_keymap]]
on   = [ "e" ]
run = "plugin searchjump autocd"
desc = "searchjump mode auto jump"
