###################
# Plugin Specific #
###################
[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Toggle Maximize preview pane"

[[mgr.prepend_keymap]]
on = [ "l" ]
run = "plugin bypass smart-enter"
desc = "Open a file, or recursively enter child directory, skipping children with only a single subdirectory"

###################
# Shell Utilities #
###################
[[mgr.prepend_keymap]]
on  = "Y"
run = 'shell -- ripdrag -axn "$@"'

[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
desc = "Copy paths to clipboard"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel 2>/dev/null || echo $HOME)"'
desc = "Open git root directory"

#################
# Fuzzy finders #
#################
[[mgr.prepend_keymap]]
on   = [ "f", "f" ]
run  = "search --via=fd --args='-H'"
desc = "Fuzzy find files"

[[mgr.prepend_keymap]]
on   = [ "f", "d" ]
run  = "plugin fuzzychild"
desc = "Fuzzy search child directories"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run = "plugin searchjump autocd"
desc = "searchjump mode auto jump"
