[manager]
ratio = [1, 3, 4] # 1/8 width for parent, 3/8 width for current, 4/8 width for preview
sort_by = "natural"
sort_dir_first = true
show_hidden = true # show hidden files
# linemode = "size" # show the size besides filename
show_symlink = true # show the symlink for the file/directory
scrolloff = 10 # number of lines to keep above and below the cursor
mouse_events = [ "click", "scroll", "touch", "move","drag"]

[[manager.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm
''', "yank" ]

[[manager.prepend_keymap]]
on = [ "g", "r" ]
run = '''
	shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
'''

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal" ] },

	{ mime = "*", use = [ "open" ] },
]

[opener]
open = [
	{ run = 'open "$@"', block = true, desc = "Open" },
]

[plugin]
prepend_previewers = [
  # Use glow to preview Markdown files
  { name = "*.md", run = "glow" },
  { mime = "audio/*",   run = "exifaudio"},
]
append_previewers = [
  { name = "*", run = "hexyl" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[preview]
tab_size        = 2
max_width       = 1000
max_height      = 1500
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
